// Code generated by "stringer -type=Format -output=format_string.gen.go"; DO NOT EDIT.

package screenshot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PNG-0]
	_ = x[UNKNOWN-1]
}

const _Format_name = "PNGUNKNOWN"

var _Format_index = [...]uint8{0, 3, 10}

func (i Format) String() string {
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
