// Code generated by "stringer -type=ScreenshotFormat -output=screenshot_format_string.gen.go"; DO NOT EDIT.

package screenshot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PNG-0]
	_ = x[UNKNOWN-1]
}

const _ScreenshotFormat_name = "PNGUNKNOWN"

var _ScreenshotFormat_index = [...]uint8{0, 3, 10}

func (i ScreenshotFormat) String() string {
	if i < 0 || i >= ScreenshotFormat(len(_ScreenshotFormat_index)-1) {
		return "ScreenshotFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScreenshotFormat_name[_ScreenshotFormat_index[i]:_ScreenshotFormat_index[i+1]]
}
