// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package textproc

import (
	"context"
)

type Querier interface {
	AllWords(ctx context.Context, arg AllWordsParams) ([]AllWordsRow, error)
	InsertWord(ctx context.Context, value string) (InsertWordRow, error)
}

var _ Querier = (*Queries)(nil)
