// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	CreateWord(ctx context.Context, value string) (CreateWordRow, error)
	CreateWordBatch(ctx context.Context, name string) (CreateWordBatchRow, error)
	ListWordBatches(ctx context.Context, arg ListWordBatchesParams) ([]ListWordBatchesRow, error)
	ListWordFrequencies(ctx context.Context, arg ListWordFrequenciesParams) ([]ListWordFrequenciesRow, error)
	ListWordRankings(ctx context.Context, arg ListWordRankingsParams) ([]ListWordRankingsRow, error)
	ListWords(ctx context.Context, arg ListWordsParams) ([]ListWordsRow, error)
}

var _ Querier = (*Queries)(nil)
